# Generated by Django 3.0.8 on 2020-10-25 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pseudonym', models.CharField(max_length=40, null=True, verbose_name='Pseudonym')),
                ('name', models.CharField(blank=True, max_length=60, null=True, verbose_name='name')),
                ('year', models.IntegerField(null=True)),
                ('day_payment', models.DateField()),
                ('document', models.FileField(null=True, upload_to='%Y/%m/%d/')),
            ],
        ),
        migrations.CreateModel(
            name='changing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(null=True)),
                ('login', models.BooleanField(blank=True)),
                ('parol', models.BooleanField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='month',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('published', models.DateTimeField(auto_now_add=True, db_index=True, null=True, verbose_name='published date')),
                ('name', models.CharField(max_length=50, null=True)),
                ('login', models.CharField(max_length=50, null=True)),
                ('parol', models.CharField(max_length=50, null=True)),
                ('pseudonym', models.CharField(max_length=50, null=True)),
                ('number', models.IntegerField(null=True, verbose_name='Номер телефона')),
            ],
        ),
        migrations.CreateModel(
            name='security',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parol', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s', models.CharField(db_index=True, max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='storage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(null=True)),
                ('year', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='subscribersbot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(null=True)),
                ('login', models.CharField(max_length=100, null=True)),
                ('parol', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='typing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(null=True)),
                ('login', models.BooleanField(blank=True)),
                ('parol', models.BooleanField(blank=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Greeting',
        ),
        migrations.AddField(
            model_name='account',
            name='month',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='hello.month'),
        ),
        migrations.AddField(
            model_name='account',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='hello.Status', verbose_name='status'),
        ),
    ]
