# Generated by Django 3.0.8 on 2020-11-02 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0002_auto_20201025_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='day_payment',
            field=models.DateField(verbose_name='Дата оплата'),
        ),
        migrations.AlterField(
            model_name='account',
            name='month',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='hello.month', verbose_name='Месяц'),
        ),
        migrations.AlterField(
            model_name='account',
            name='name',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='account',
            name='pseudonym',
            field=models.CharField(max_length=40, null=True, verbose_name='Псевдоним'),
        ),
        migrations.AlterField(
            model_name='account',
            name='status',
            field=models.ForeignKey(default=2000, on_delete=django.db.models.deletion.PROTECT, to='hello.Status', verbose_name='Статус'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='account',
            name='year',
            field=models.IntegerField(null=True, verbose_name='Год'),
        ),
    ]
