# Generated by Django 3.0.8 on 2020-11-02 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0003_auto_20201102_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='s',
            field=models.CharField(blank=True, db_index=True, max_length=20, unique=True),
        ),
    ]
