# Generated by Django 3.0.8 on 2020-11-02 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0007_auto_20201102_1715'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='name',
        ),
    ]
