# Generated by Django 3.0.8 on 2020-11-02 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0008_auto_20201102_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='number',
            field=models.IntegerField(max_length=30, null=True, verbose_name='Номер телефона'),
        ),
    ]
