# Generated by Django 3.0.8 on 2020-11-03 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0014_auto_20201103_1027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='number',
            field=models.CharField(blank=True, max_length=17, verbose_name=''),
        ),
    ]
