# Generated by Django 3.0.8 on 2020-11-03 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0016_auto_20201103_1057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='code',
            field=models.CharField(blank=True, max_length=17, verbose_name=''),
        ),
    ]
