# Generated by Django 3.0.8 on 2020-11-03 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0018_auto_20201103_1128'),
    ]

    operations = [

    ]
