# Generated by Django 3.0.8 on 2020-11-03 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0024_auto_20201103_1952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='day_payment',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Дата оплата'),
        ),
    ]
