# Generated by Django 3.0.8 on 2020-11-04 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0025_auto_20201103_2309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='day_payment',
            field=models.CharField(max_length=40, null=True, verbose_name='Дата оплата'),
        ),
    ]
