# Generated by Django 3.0.8 on 2020-11-04 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0026_auto_20201104_0721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='number',
            field=models.IntegerField(blank=True, verbose_name=''),
        ),
    ]
