# Generated by Django 3.0.8 on 2020-11-04 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0027_auto_20201104_0739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='code',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name=''),
        ),
    ]
