# Generated by Django 3.0.8 on 2020-11-04 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0029_auto_20201104_0805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='s',
            field=models.CharField(db_index=True, max_length=20, null=True),
        ),
    ]
