# Generated by Django 3.0.8 on 2020-11-08 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0030_auto_20201104_1836'),
    ]

    operations = [
        migrations.CreateModel(
            name='sendmessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('select', models.CharField(max_length=50, null=True)),
                ('message', models.TextField(max_length=500, null=True)),
            ],
        ),
    ]
