# Generated by Django 3.0.8 on 2020-11-08 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0031_sendmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='published',
            field=models.DateTimeField(auto_now_add=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='summa',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='card_number',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='date_card',
            field=models.DateField(default='2020-09-04'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='owner_card',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='prefix',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='type_payment',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='valute_card',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
