# Generated by Django 3.0.8 on 2020-11-10 02:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0032_auto_20201108_1920'),
        ('hello', '0033_auto_20201108_1921'),
    ]

    operations = [
    ]
