# Generated by Django 3.0.8 on 2020-11-10 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0034_merge_20201110_0721'),
    ]

    operations = [
        migrations.CreateModel(
            name='card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pseudonym', models.CharField(max_length=50, null=True)),
                ('card_number', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='account',
            name='card_number',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
