# Generated by Django 3.0.8 on 2020-11-11 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0037_auto_20201111_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='published',
            field=models.DateTimeField(db_index=True, null=True, verbose_name='published date'),
        ),
    ]
