# Generated by Django 3.0.8 on 2020-11-15 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0038_auto_20201111_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='date_card',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
