# Generated by Django 3.0.8 on 2020-11-19 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0039_auto_20201115_1653'),
    ]

    operations = [
        migrations.CreateModel(
            name='action_story',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, null=True)),
                ('obj', models.CharField(max_length=20, null=True)),
                ('pseudonym', models.CharField(max_length=50, null=True)),
                ('url', models.CharField(max_length=30, null=True)),
            ],
        ),
    ]
