# Generated by Django 3.0.8 on 2020-11-20 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0040_action_story'),
    ]

    operations = [
        migrations.CreateModel(
            name='acc_pre_value',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pseudonym', models.CharField(max_length=40, null=True, verbose_name='Псевдоним')),
                ('pse', models.CharField(max_length=100, null=True)),
                ('month', models.CharField(max_length=100, null=True)),
                ('year', models.IntegerField(null=True, verbose_name='Год')),
                ('status', models.CharField(max_length=100, null=True)),
                ('day_payment', models.CharField(max_length=40, null=True, verbose_name='Дата оплата')),
                ('document', models.FileField(null=True, upload_to='%Y/%m/%d/')),
                ('published', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('summa', models.CharField(max_length=20, null=True)),
                ('card_number', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='account',
            name='pse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='hello.Profile'),
        ),
    ]
