# Generated by Django 3.0.8 on 2020-11-20 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0041_auto_20201120_1520'),
    ]

    operations = [
        migrations.CreateModel(
            name='stories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('published', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('admin', models.CharField(max_length=100, null=True)),
                ('obj', models.CharField(max_length=20, null=True)),
                ('text', models.TextField(null=True)),
            ],
        ),
    ]
