# Generated by Django 3.0.8 on 2020-11-22 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0043_auto_20201122_1016'),
    ]

    operations = [
        migrations.CreateModel(
            name='prof_pre_value',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=50, null=True, verbose_name='Логин')),
                ('parol', models.CharField(max_length=50, null=True, verbose_name='Парол')),
                ('pseudonym', models.CharField(max_length=50, null=True, verbose_name='Псевдоним')),
                ('number', models.IntegerField(blank=True, verbose_name='')),
                ('code', models.CharField(blank=True, max_length=5, null=True, verbose_name='t')),
                ('name', models.CharField(blank=True, max_length=50, verbose_name='name')),
                ('prefix', models.CharField(max_length=20, null=True)),
                ('type_payment', models.CharField(max_length=50, null=True)),
                ('valute_card', models.CharField(max_length=10, null=True)),
                ('card_number', models.CharField(max_length=30, null=True)),
                ('date_card', models.CharField(blank=True, max_length=20, null=True)),
                ('owner_card', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
