# Generated by Django 3.0.8 on 2020-12-03 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0044_prof_pre_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prof_pre_value',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
