# Generated by Django 3.1.7 on 2021-02-27 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0045_auto_20201203_1422'),
    ]

    operations = [
        migrations.CreateModel(
            name='contract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(null=True, upload_to='main/')),
            ],
        ),
    ]
