# Generated by Django 3.1.7 on 2021-04-09 01:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0049_video_pseudonym'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Audio',
        ),
        migrations.DeleteModel(
            name='Video',
        ),
    ]
