# Generated by Django 3.1.7 on 2021-04-09 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0050_auto_20210409_0109'),
    ]

    operations = [
        migrations.CreateModel(
            name='Audio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('composition', models.CharField(max_length=200, null=True, verbose_name='Произведение')),
                ('artist', models.CharField(max_length=100, null=True, verbose_name='Артист')),
                ('autor_music', models.CharField(max_length=100, null=True, verbose_name='Автор музыки')),
                ('autor_text', models.CharField(max_length=100, null=True, verbose_name='Автор текста')),
                ('album', models.CharField(max_length=100, null=True, verbose_name='Альбом')),
                ('isrc', models.CharField(max_length=100, null=True, verbose_name='ISRC (код)')),
                ('genre', models.CharField(max_length=50, null=True, verbose_name='Жанр')),
                ('copyright', models.CharField(max_length=100, null=True, verbose_name='Авторские права')),
                ('related_rights', models.CharField(max_length=100, null=True, verbose_name='Смежные права')),
                ('upc', models.CharField(max_length=100, null=True, verbose_name='UPC')),
                ('release_date', models.CharField(max_length=100, null=True, verbose_name='Дата релиза')),
                ('territory', models.CharField(max_length=100, null=True, verbose_name='Территория')),
                ('link', models.CharField(max_length=200, null=True, verbose_name='Ссылка на файл')),
                ('pseudonym', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(blank=True, max_length=5, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('composition', models.CharField(max_length=200, null=True, verbose_name='Произведение')),
                ('type', models.CharField(max_length=100, null=True, verbose_name='Тип')),
                ('artist', models.CharField(max_length=100, null=True, verbose_name='Артист')),
                ('isrc', models.CharField(max_length=100, null=True, verbose_name='ISRC (код)')),
                ('producer', models.CharField(max_length=100, null=True, verbose_name='Режиссер-постановщик')),
                ('operator', models.CharField(max_length=100, null=True, verbose_name='Оператор-постановщик')),
                ('autor_script', models.CharField(max_length=100, null=True, verbose_name='Автор сценария')),
                ('painter', models.CharField(max_length=100, null=True, verbose_name='Художник-постановщик')),
                ('copyright', models.CharField(max_length=100, null=True, verbose_name='Авторские права')),
                ('release_date', models.CharField(max_length=100, null=True, verbose_name='Дата релиза')),
                ('territory', models.CharField(max_length=100, null=True, verbose_name='Территория')),
                ('link', models.CharField(max_length=200, null=True, verbose_name='Ссылка на файл')),
                ('pseudonym', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(blank=True, max_length=5, null=True)),
            ],
        ),
    ]
